version: 2.1

orbs:
  jira: circleci/jira@1.3.1
  
executors:
  container: 
    docker:
      - image: cimg/<< parameters.jdk-version >> 

jobs:         
  build-test:  
    parameters:
      jdk-version:
        type: enum
        default: "openjdk:11.0" 
        enum: ["openjdk:11.0"]
      enviromente:
        type: enum
        default: "development" 
        enum: ["development","production"]   
    executor:
      name: container 
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: test
          command: mvn test
  deploy:
    enviromente:
      type: enum
      default: "development" 
      enum: ["development","production"]  
    executor:
      name: container
    steps:
      - run:
          name: deploy
          command: mvn verify
workflows:
  java-xml-jira-clock: 
    jobs: 
      - build-test:    
          post-steps:
            - jira/notify:
              environment_type: << parameters.enviroment >>               
      - deploy:
          post-steps:
            - jira/notify:
              environment_type: << parameters.enviroment >>       
          type: approval 
          requires: 
            - build                