version: 2.1

orbs:
  jira: circleci/jira@1.3.1
  
executors:
  container: 
    docker:
      - image: cimg/<< parameters.jdk-version >> 

jobs:
  check:
    parameters:
      jdk-version:
        type: enum
        default: "openjdk:11.0" 
        enum: ["openjdk:11.0"]
      enviromente:
        type: enum
        default: "development" 
        enum: ["development","production"]          
    executor:
      name: container
    steps:
      - checkout  
  test: 
    executor:
      name: container
    steps:
      - run:
          name: test
          command: mvn test
  build:  
    executor:
      name: container 
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: test
          command: mvn test

workflows:
  java-xml-jira-clock: 
    jobs: 
      - test:
          post-steps:        
           - jira/notify:
             environment_type: << parameters.enviroment >>      
      - build:
          post-steps:
            - jira/notify:
              environment_type: << parameters.enviroment >> 
          requires: 
            - test                 
      - deploy:
          post-steps:
            - jira/notify:
              environment_type: << parameters.enviroment >>       
          type: approval 
          requires: 
            - build                