version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
orbs:
  jira: circleci/jira@1.3.1
workflows:
  java-xml-jira-clock: 
    jobs:
      - build-and-test:
          post-steps:
            - jira/notify:
                - environment_type: production